/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

const React = require('react');
const { useGLTF } = require('@react-three/drei');
const { TextureLoader } = require('three');
const gltf = require('../static/GAMEBOY.glb');
const logoImage = require('../static/logo.png');

function Model(props) {
  const { nodes, materials } = useGLTF(gltf);
  materials.Base.color = props.color;
  const logoTexture = new TextureLoader().load(logoImage);
  logoTexture.flipY = false;
  materials.Logo.map = logoTexture;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo.geometry} material={materials.Logo} position={[-0.09, -0.83, 0.24]} />
      <mesh geometry={nodes.screen.geometry} material={materials.Screen} position={[-0.02, 1.17, 0.46]} scale={[0.99, 0.99, 0.03]} />
      <mesh geometry={nodes.dpad.geometry} material={materials.dpad} position={[-0.93, -0.85, 0.43]} scale={0.12} />
      <mesh geometry={nodes.b.geometry} material={materials.Buttons} position={[0.56, -0.93, 0.43]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.a.geometry} material={materials.Buttons} position={[1.07, -0.69, 0.43]} rotation={[Math.PI / 2, 0, 0]} scale={0.91} />
      <mesh geometry={nodes.select.geometry} material={nodes.select.material} position={[-0.46, -1.6, 0.48]} rotation={[0, 0, 0.46]} scale={[0.94, 0.94, 0.29]} />
      <mesh geometry={nodes.start.geometry} material={nodes.start.material} position={[0.07, -1.6, 0.48]} rotation={[0, 0, 0.46]} scale={[0.93, 0.93, 0.29]} />
      <mesh geometry={nodes.shell.geometry} material={materials.Base} position={[-0.09, -0.83, 0.24]} />
    </group>
  )
}

module.exports = Model;

useGLTF.preload(gltf)
